spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  data:
    rest:
     base-path: /api
  boot:
    admin:
      client:
          url: http://localhost:9090
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: threaddump,heapdump


  security:
   oauth2:
    resourceserver:
     jwt:
       jwk-set-uri: http://localhost:9000/oauth2/jwks